#!/bin/bash/


API_URL="https://pokeapi.co/api/v2/pokemon/2/"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

wget -O OUTPUT_FILE API_URL

if [ $? -ne 0 ]; then
	echo "Failed to fetch data from API" >> "$ERROR_FILE"
	exit 1
fi
